kind: pipeline
name: push_routine

steps:
- name: run_tests
  image: "python:3.7-alpine"
  commands:
  - python -m pip install -r requirements.txt
  - pytest --cov --cov-config=.coveragerc
- name: check_image
  image: "docker:18.09.7"
  commands:
  - docker build -t fileshelter .
  - docker run fileshelter pytest --cov --cov-config=.coveragerc
